# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

try:
    from proto import nexxtts_pb2 as nexxtts__pb2
except ImportError:
    from cloud.proto import nexxtts_pb2 as nexxtts__pb2

GRPC_GENERATED_VERSION = "1.80.0"

try:
    import grpcio

    GRPC_VERSION = grpcio.__version__
except (ImportError, AttributeError):
    GRPC_VERSION = "1.80.0"


class NexTTSStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTTS = channel.unary_stream(
            "/nexxtts.v1.NexTTS/StreamTTS",
            request_serializer=nexxtts__pb2.StreamTTSRequest.SerializeToString,
            response_deserializer=nexxtts__pb2.AudioChunk.FromString,
            _registered_method=True,
        )
        self.GenerateTTS = channel.unary_unary(
            "/nexxtts.v1.NexTTS/GenerateTTS",
            request_serializer=nexxtts__pb2.GenerateTTSRequest.SerializeToString,
            response_deserializer=nexxtts__pb2.GenerateTTSResponse.FromString,
            _registered_method=True,
        )
        self.Transcribe = channel.unary_unary(
            "/nexxtts.v1.NexTTS/Transcribe",
            request_serializer=nexxtts__pb2.TranscribeRequest.SerializeToString,
            response_deserializer=nexxtts__pb2.TranscribeResponse.FromString,
            _registered_method=True,
        )
        self.ListVoices = channel.unary_unary(
            "/nexxtts.v1.NexTTS/ListVoices",
            request_serializer=nexxtts__pb2.ListVoicesRequest.SerializeToString,
            response_deserializer=nexxtts__pb2.ListVoicesResponse.FromString,
            _registered_method=True,
        )
        self.CreateVoice = channel.unary_unary(
            "/nexxtts.v1.NexTTS/CreateVoice",
            request_serializer=nexxtts__pb2.CreateVoiceRequest.SerializeToString,
            response_deserializer=nexxtts__pb2.Voice.FromString,
            _registered_method=True,
        )
        self.DeleteVoice = channel.unary_unary(
            "/nexxtts.v1.NexTTS/DeleteVoice",
            request_serializer=nexxtts__pb2.DeleteVoiceRequest.SerializeToString,
            response_deserializer=nexxtts__pb2.Empty.FromString,
            _registered_method=True,
        )


class NexTTSServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamTTS(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GenerateTTS(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Transcribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListVoices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateVoice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteVoice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_NexTTSServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "StreamTTS": grpc.unary_stream_rpc_method_handler(
            servicer.StreamTTS,
            request_deserializer=nexxtts__pb2.StreamTTSRequest.FromString,
            response_serializer=nexxtts__pb2.AudioChunk.SerializeToString,
        ),
        "GenerateTTS": grpc.unary_unary_rpc_method_handler(
            servicer.GenerateTTS,
            request_deserializer=nexxtts__pb2.GenerateTTSRequest.FromString,
            response_serializer=nexxtts__pb2.GenerateTTSResponse.SerializeToString,
        ),
        "Transcribe": grpc.unary_unary_rpc_method_handler(
            servicer.Transcribe,
            request_deserializer=nexxtts__pb2.TranscribeRequest.FromString,
            response_serializer=nexxtts__pb2.TranscribeResponse.SerializeToString,
        ),
        "ListVoices": grpc.unary_unary_rpc_method_handler(
            servicer.ListVoices,
            request_deserializer=nexxtts__pb2.ListVoicesRequest.FromString,
            response_serializer=nexxtts__pb2.ListVoicesResponse.SerializeToString,
        ),
        "CreateVoice": grpc.unary_unary_rpc_method_handler(
            servicer.CreateVoice,
            request_deserializer=nexxtts__pb2.CreateVoiceRequest.FromString,
            response_serializer=nexxtts__pb2.Voice.SerializeToString,
        ),
        "DeleteVoice": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteVoice,
            request_deserializer=nexxtts__pb2.DeleteVoiceRequest.FromString,
            response_serializer=nexxtts__pb2.Empty.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "nexxtts.v1.NexTTS", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("nexxtts.v1.NexTTS", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class NexTTS(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamTTS(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/nexxtts.v1.NexTTS/StreamTTS",
            nexxtts__pb2.StreamTTSRequest.SerializeToString,
            nexxtts__pb2.AudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GenerateTTS(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/nexxtts.v1.NexTTS/GenerateTTS",
            nexxtts__pb2.GenerateTTSRequest.SerializeToString,
            nexxtts__pb2.GenerateTTSResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Transcribe(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/nexxtts.v1.NexTTS/Transcribe",
            nexxtts__pb2.TranscribeRequest.SerializeToString,
            nexxtts__pb2.TranscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListVoices(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/nexxtts.v1.NexTTS/ListVoices",
            nexxtts__pb2.ListVoicesRequest.SerializeToString,
            nexxtts__pb2.ListVoicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateVoice(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/nexxtts.v1.NexTTS/CreateVoice",
            nexxtts__pb2.CreateVoiceRequest.SerializeToString,
            nexxtts__pb2.Voice.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteVoice(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/nexxtts.v1.NexTTS/DeleteVoice",
            nexxtts__pb2.DeleteVoiceRequest.SerializeToString,
            nexxtts__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
